import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Drawer from "@/components/Drawer/Drawer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children }: LayoutProps<"/dashboard">) {
  return (
        <div className="drawer h-screen lg:drawer-open">
          <input type="checkbox" className="drawer-toggle" id="dashboard-drawer" />
          <Drawer />
          <div className="drawer-content flex h-screen flex-col ">
            {children}
          </div>
        </div>
  );
}
